Hardcode STREAM KEY as environment variable
GRVYDEV/Lightspeed-ingest pull request #37
Opened 2021-02-01 05:06 UTC by nitrag

Let's us hardcode a stream key that won't change so it can survive docker restarts.

ISSUE: Why is the string prefixed with `77-`?

2021-02-01 16:46 UTC, GRVYDEV commented
Stream key format is CHANNELID-KEY. We cannot hardcode the keys we need to generate them. As of right now the key is persisted in a file so there should be a way to persist that file through docker restarts

2021-02-01 17:30 UTC, nitrag commented
Hmm, we can do persistence through docker volume mounting. Is there a reason we shouldn't be able to hardcode though if the user want to provide it? Not having this ability will make automated deployments (terraform) complicated and prevent the infrastructure as a whole form being stateless.

2021-02-01 17:32 UTC, GRVYDEV commented
> Hmm, we can do persistence through docker volume mounting. Is there a reason we shouldn't be able to hardcode though if the user want to provide it? Not having this ability will make automated deployments (terraform) complicated and prevent the infrastructure as a whole form being stateless.

Can you elaborate on what you mean by automated deployments?

2021-02-01 17:56 UTC, nitrag commented
> Can you elaborate on what you mean by automated deployments?

Terraform is an example. Automated isn't the correct word but I meant in the sense of a single-click "deploy". Persisting the stream key (hash file), besides the difficulty to be able to easily grab it after it is created, would prevent the ability for this project to be **stateless**. Meaning, no persistent filesystem required. Which is a huge benefit for deployments in the cloud.

Unless there is a specific reason we cannot specify the Stream Key beforehand, there is no reason to not allow it to be (optionally) hardcoded as this PR allows. The alternative is to use an entrypoint to the docker container that creates the hash file (from an ENV variable) before application start, but that seems convoluted.

Real world example:

1. Sign-up for Digitial Ocean
2. Get API keys
3. Insert your api keys into a terraform variables file `variables.tf` along with your other custom ENV variables (Stream key).
4. Run `terraform apply`
5. 5 minutes later you have Project Lighspeed stack running in Digital Ocean cloud.
6. Tear it down, `terraform destroy`.
7. Spin it up somewhere else: AWS, or Google, etc.

2021-02-05 02:02 UTC, nitrag commented
@GRVYDEV I think this is ready for your Review/Approval

2021-02-05 04:15 UTC, GRVYDEV requested changes
Looks good but see my internal comment

2021-02-05 04:15 UTC, GRVYDEV commented on src/main.rs
> +    let _ = connection::read_stream_key(true, stream_key_env);
Hm okay I see what you are doing here but I am not sure this is the most elegant solution. Couldn't we just read the value of the ENV var on startup and remove the need for the additional argument in the function?

2021-02-05 04:22 UTC, GRVYDEV commented on src/main.rs
> +    let _ = connection::read_stream_key(true, stream_key_env);
Okay I see why you did it that way now. Id still like to try and find a better solution

2021-02-09 01:47 UTC, merged